### ISSUE TITLE
One Click: Model -> App Creator

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/io3d-blender-to-webvr#1]
Inspired by https://gist.github.com/Utopiah/a2b9c6ecdb24ca8fd6f4f41a9c0eb32e
twittered on https://twitter.com/utopiah/status/896013359702835200
we want to create a single button app which publishes / updates a blender scene into app creator.
process:

1. export scene using gltf exporter (https://github.com/KhronosGroup/glTF-Blender-Exporter)
2. upload files into 3d.io storage
  2.1. get credentials using publishable api key
  2.2. upload files to S3 using credentials
3. create HTML file including a-scene ready for app creator
4. upload HTML file to 3d.io storage
5. use the app.3d.io API to get a short app ID (ask martin)
6. store the short app ID in the blender scene so that we can use it for syncing purposes later
7. open short app ID in app creator

**Comment by tomas-polach** [comment]
jsonrpc call in python by @frederic-schwarz https://github.com/archilogic-com/autofurnishing/blob/replacement-api/prototype/replacement/jsonrpc.py

**Comment by Aadjou** [comment]
Closing because not sure if this will be continued
